Issue 1 create an entry
DavidKyong/code-journal pull request #5
Opened 2023-05-30 22:03 UTC by DavidKyong

![Recording 2023-05-30 at 14 59 03](https://github.com/DavidKyong/code-journal/assets/77517004/083cec22-c5b6-48fe-8908-263aee21f1f2)

2023-05-30 22:16 UTC, DavidKyong commented
![Recording 2023-05-30 at 15 15 01](https://github.com/DavidKyong/code-journal/assets/77517004/b8bfe975-f481-4be4-aa54-48f6c1bba4bb)

2023-05-30 22:20 UTC, shawnkost requested changes
Looking good so far David! A few changes requested here below. Make sure to also fix the background colors I told you about in our messages. Let me know if you have any questions!

2023-05-30 22:20 UTC, shawnkost commented on .devcontainer/devcontainer.json
> +	// "remoteUser": "root"
Nothing should have changed inside of this `devcontainer.json` file. Please revert back to what was there before.

2023-05-30 22:20 UTC, shawnkost commented on css/layout.css
> +  font-family: "open sans";
Need to set a backup font

2023-05-30 22:20 UTC, shawnkost commented on css/styles.css
> +  font-family: "proza libre";
Need to set a backup font

2023-05-30 22:20 UTC, shawnkost commented on css/styles.css
> +  }
Be careful when using negative margin. If you're using negative margin, then you're probably doing something "hacky" to get this to work

2023-05-30 22:20 UTC, shawnkost commented on index.html
> +      </div>
This should be inside your `div` with `data-view="entry-form"`

2023-05-30 22:20 UTC, shawnkost commented on index.html
> +              <input id="title" name="pageTitle" required>
Needs a `type` attribute

2023-05-30 22:20 UTC, shawnkost commented on index.html
> +              <input id="url" name="photoURL" required>
Needs a `type` attribute

2023-05-30 22:20 UTC, shawnkost commented on index.html
> +              <label for="save"></label><br>
Don't need a label here, since there's no text inside

2023-05-30 22:20 UTC, shawnkost commented on js/.devcontainer/devcontainer.json
> +}
Delete this whole `.devcontainer` folder that's inside of your `js` folder

2023-05-30 22:20 UTC, shawnkost commented on js/main.js
> +  event.preventDefault();
No need for `event.preventDefault` here

2023-05-30 22:20 UTC, shawnkost commented on js/main.js
> +  data.entries.push(formValue);
`formValue` should be getting added to the beginning of the array

2023-05-30 22:20 UTC, shawnkost commented on js/main.js
> +  event.target.reset();
`event.target` will refer to the element that was interacted with, which in this case, I believe would be the submit button. I would just do `$form.reset()`

2023-05-31 01:20 UTC, shawnkost approved these changes
👍🏻

2023-05-31 01:37 UTC, merged