Issue 3 edit an entry
DavidKyong/code-journal pull request #7
Opened 2023-06-04 18:59 UTC by DavidKyong

Screen record in slack

2023-06-04 20:51 UTC, shawnkost requested changes
One change here David! Let me know if you have any questions

2023-06-04 20:51 UTC, shawnkost commented on js/main.js
> +  location.reload();
You should not be reloading the page. We use `event.preventDefault` to specifically stop the page from refreshing. You should be finding the current `li` that exists on the DOM, and replacing it with the newly edited entry.

2023-06-04 23:55 UTC, DavidKyong commented on js/main.js
> +  location.reload();
I think I fixed the problem, but when I do replace the old form with the updated form, how come I have to set the data-entry-id back to the same entry-id I am fixing?

2023-06-05 00:55 UTC, shawnkost requested changes
One more change!

2023-06-05 00:55 UTC, shawnkost commented on js/main.js
> +    updateValue.setAttribute('data-entry-id', updateEntryId);
This should be happening inside of  `renderEntry`

2023-06-07 03:12 UTC, shawnkost requested changes
One small edit here!

2023-06-07 03:12 UTC, shawnkost commented on js/main.js
> +// let updateEntryId;
Delete all old code!

2023-06-07 03:15 UTC, shawnkost approved these changes
👍🏻

2023-06-07 03:16 UTC, merged